name: Publish Docker Image

on:
  push:
    branch: ["main"]
    

jobs:
  build-test:
  #  defenition plateform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
  # instructions
      - run: npm ci
      - run: npm run build
      - run: npm test